# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "customers", :force => true do |t|
    t.column "name",        :string,               :null => false
    t.column "nif",         :string
    t.column "phone",       :string
    t.column "email",       :string
    t.column "address",     :string
    t.column "private_key", :string, :limit => 32
  end

  create_table "invoice_lines", :force => true do |t|
    t.column "invoice_id",  :integer
    t.column "quantity",    :integer,                               :default => 1
    t.column "description", :string
    t.column "price",       :decimal, :precision => 8, :scale => 2, :default => 0.0
  end

  create_table "invoices", :force => true do |t|
    t.column "customer_id", :integer,                                                 :null => false
    t.column "date",        :date
    t.column "fiscal_year", :integer
    t.column "number",      :integer
    t.column "irpf",        :decimal, :precision => 8, :scale => 2, :default => 15.0
    t.column "iva",         :decimal, :precision => 8, :scale => 2, :default => 16.0
  end

  create_table "users", :force => true do |t|
    t.column "name",                      :string
    t.column "address",                   :text
    t.column "nif",                       :string
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
